const LEMON_SQUEEZY_URL = process.env.NEXT_PUBLIC_LEMON_SQUEEZY_URL
const LEMON_SQUEEZY_SIGNING_KEY = process.env.LEMON_SQUEEZY_SIGNING_KEY || ""

export {
  LEMON_SQUEEZY_URL,
  LEMON_SQUEEZY_SIGNING_KEY,
}
